<?php

namespace App\Http\Controllers;

use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Masterminds\HTML5\Exception;

class Faltas extends Jugadores
{
    /**
     * IndexAddPalabras constructor.
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Trata que acción hay que realizar y la ejecuta
     * @return false|Application|Factory|View|string
     */
    public function index(Request $request)
    {
        switch ($request->input('accion')) {
            case "mostarEquipo":
                return $this->mostarEquipo($request->input('equipo'));
            case "mostarJugadoresEquipo":
                return $this->mostarJugadores($request->input('equipo'));
            case "addFalta":
                return $this->addFaltas($request->input('equipo'),$request->input('jugadoresFalta'),$request->input('fecha'));
            default:
                return $this->consultar();
        }
    }

    /**
     * Obtiene los parametros de entrada y devuelve el view del controller
     * @return Application|Factory|View
     */
    private function consultar()
    {
        $ajaxUrl = url()->full();
        $arrViewData = [
            'ajaxUrl' => $ajaxUrl
        ];
        return view('faltas', $arrViewData);
    }

    /**
     * Consulta el contador de $equipos creadas en glosarios
     * @param Request $request
     * @return false|string Respuesta
     */
    public function mostarEquipo(string $equipo)
    {
        return parent::mostarEquipo($equipo); // TODO: Change the autogenerated stub

    }

    public function mostarJugadores($equipo)
    {
        return parent::mostarJugadores($equipo); // TODO: Change the autogenerated stub
    }

    public function addFaltas($equipo, $jugadores, $fecha){
        $arrayFaltas = explode(',', $jugadores);

        foreach ($arrayFaltas as $jugador){
            $insertado = DB::table('faltas_asistencia')->insert([
                'id_jugador' => $jugador,
                'fecha' => $fecha,
                'id_equipoSan' => $equipo
            ]);

            $faltasTotales = DB::table('jugadores')
                ->select('faltasTotales')
                ->where('id_jugador', $jugador)
                ->get()
                ->first();

            $faltasActuales = ($faltasTotales->faltasTotales);
            $faltasActuales = $faltasActuales + 1;

            DB::table('jugadores')
                ->where('id_jugador', '=', $jugador)
                ->update([
                    'faltasTotales' => $faltasActuales
                ]);


        }

    }
}
